namespace: school-ns


replicas: 2
deployment:
  name: school-app-deployment
  labels:
    app: school-app
  port:  80
  image:
    repository: kalyantwt/school
    tag: v1


service:
  app: school-app
  type: LoadBalancer
